task: Cifar10_Ours
random_seed: 0
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 350
save_on_epochs: [100, 200, 300]
optimizer: SGD
log_interval: 100
scheduler: False
pretrained: True

poisoning_proportion: 1
backdoor_label: 8

loss_balance: fixed
fixed_scales: {'backdoor': 0.5, 'normal': 0.5}

save_model: True
log: True
tb: True

transform_train: True

fl: True
fl_no_models: 10
fl_local_epochs: 2
fl_total_participants: 10
fl_eta: 1
fl_q: 0.1
fl_number_of_adversaries: 6
fl_weight_scale: 1.6667

# clean_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
clean_set_dataset: GTSRB
clean_ratio: 0.1

ours: True
ours_lbd: 1
attacker_train_ratio: 0.9
r_interval: 0.1
nc_steps: 100
max_threads: 64
attack_start_epoch: 1

loss_tasks:
  - backdoor
  - normal

